global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']

  - job_name: 'custom_model_metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Points to your host machine's exporter